server:
  port: 8765

spring:
  application:
    name: user-service

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: http://cloud:123456@localhost:8761/eureka/

