server:
  port: 8764

spring:
  application:
    name: eureka-feign
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: http://cloud:123456@localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
