server:
  port: 8763

spring:
  application:
    name: ribbon

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: http://cloud:123456@localhost:8761/eureka/

service-url:
  eureka-client: http://eureka-client/