spring:
  application:
    name: order-service
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: global-tx-group
